spring:
  datasource:
    url: ${JDBC_URL:jdbc:h2:file:./database/shop}
    driver-class-name: ${DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: ${HBM_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${HBM_DIALECT:org.hibernate.dialect.H2Dialect}
  h2:
    console:
      enabled: true